spring.application.name=NutriWeb
# URL que copiaste de Supabase
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres?user=postgres.ltfqijgriuxmzxauaxeo&password=12152198Ma!!
spring.datasource.username=postgres
# La contrasena que elegiste al crear el proyecto
spring.datasource.password=12152198Ma!!

# Configuracion de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
